export let products = [
  {
    id: 1,
    name: 'Laptop Lenovo IdeaPad 3',
    category: 'Computadores',
    price: 2500000,
    stock: 15,
    brand: 'Lenovo',
    description: 'Laptop con procesador Ryzen 5, 8GB RAM y 512GB SSD',
  },
  {
    id: 2,
    name: 'iPhone 13',
    category: 'Celulares',
    price: 3200000,
    stock: 10,
    brand: 'Apple',
    description: 'Smartphone con chip A15 Bionic y cámara dual de 12MP',
  },
  {
    id: 3,
    name: 'Samsung Galaxy S22',
    category: 'Celulares',
    price: 3000000,
    stock: 12,
    brand: 'Samsung',
    description: 'Pantalla AMOLED 120Hz, 8GB RAM y cámara triple',
  },
  {
    id: 4,
    name: 'Audífonos Sony WH-1000XM4',
    category: 'Audio',
    price: 1200000,
    stock: 20,
    brand: 'Sony',
    description: 'Audífonos inalámbricos con cancelación de ruido',
  },
  {
    id: 5,
    name: 'Monitor LG 24"',
    category: 'Accesorios',
    price: 800000,
    stock: 18,
    brand: 'LG',
    description: 'Monitor Full HD de 24 pulgadas con panel IPS',
  },
  {
    id: 6,
    name: 'Teclado Mecánico Redragon',
    category: 'Accesorios',
    price: 250000,
    stock: 30,
    brand: 'Redragon',
    description: 'Teclado mecánico RGB para gaming',
  },
  {
    id: 7,
    name: 'Mouse Logitech G502',
    category: 'Accesorios',
    price: 200000,
    stock: 25,
    brand: 'Logitech',
    description: 'Mouse gamer con sensor de alta precisión',
  },
  {
    id: 8,
    name: 'Tablet Samsung Galaxy Tab S7',
    category: 'Tablets',
    price: 2200000,
    stock: 8,
    brand: 'Samsung',
    description: 'Tablet con pantalla de 11 pulgadas y S Pen incluido',
  },
  {
    id: 9,
    name: 'Smartwatch Xiaomi Mi Watch',
    category: 'Wearables',
    price: 500000,
    stock: 22,
    brand: 'Xiaomi',
    description: 'Reloj inteligente con monitoreo de salud',
  },
  {
    id: 10,
    name: 'Disco Duro Externo 1TB',
    category: 'Almacenamiento',
    price: 300000,
    stock: 40,
    brand: 'Seagate',
    description: 'Disco duro portátil USB 3.0 de 1TB',
  },
];