export let cursos = [
  {
    id: 1,
    titulo: 'Auxiliar Administrativo en Salud',
    instructor: 'María López',
    categoria: 'Salud',
    duracion: '6 meses',
    lecciones: 48,
    nivel: 'Intermedio',
    precio: 120000,
    calificacion: 4.8,
    estudiantes: 320,
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb3VB0zwS2iVpA1wZ9bG_KZ_SdZ6ne3Y1mdg&s',
    descripcion: 'Aprende los procesos administrativos del sector salud.',
  },
  {
    id: 2,
    titulo: 'Primeros Auxilios',
    instructor: 'Carlos Pérez',
    categoria: 'Salud',
    duracion: '1 mes',
    lecciones: 12,
    nivel: 'Básico',
    precio: 50000,
    calificacion: 4.7,
    estudiantes: 500,
    imagen: 'https://educacionvirtual.javeriana.edu.co/documents/d/educacionvirtual/urgencias-medicas-caribe-jpg?imagePreview=1',
    descripcion: 'Actúa correctamente en emergencias médicas.',
  },
  {
    id: 3,
    titulo: 'Facturación en Salud',
    instructor: 'Ana Gómez',
    categoria: 'Administración',
    duracion: '3 meses',
    lecciones: 30,
    nivel: 'Intermedio',
    precio: 90000,
    calificacion: 4.6,
    estudiantes: 210,
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb3VB0zwS2iVpA1wZ9bG_KZ_SdZ6ne3Y1mdg&s',
    descripcion: 'Domina la facturación y cuentas médicas.',
  },
  {
    id: 4,
    titulo: 'Atención al Usuario',
    instructor: 'Luis Ramírez',
    categoria: 'Servicio',
    duracion: '2 meses',
    lecciones: 20,
    nivel: 'Básico',
    precio: 60000,
    calificacion: 4.5,
    estudiantes: 150,
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb3VB0zwS2iVpA1wZ9bG_KZ_SdZ6ne3Y1mdg&s',
    descripcion: 'Mejora la atención al cliente en salud.',
  },
  
];